/** Course catalog — subjects + common study topics. Custom names still allowed at runtime. */

const E = ["Exam review", "Final exam review"] as const;
const H = ["Homework help", "Concept review", ...E] as const;
const P = ["Practice problems", ...H] as const;
const L = ["Lab prep", "Lab report help", "Pre-lab quiz", ...E] as const;
const W = ["Essay writing", "Research paper help", "Peer review", ...E] as const;
const G = ["Grammar", "Conversation practice", "Writing", "Listening practice", ...E] as const;
const J = ["Project help", "Milestone check-in", "Presentation prep", ...E] as const;
const T = ["Practice tests", "Concept review", "Study strategies", ...E] as const;

function stem(...topics: string[]) {
  return [...topics, ...P];
}
function lab(...topics: string[]) {
  return [...topics, ...L];
}
function essay(...topics: string[]) {
  return [...topics, ...W];
}
function lang(...topics: string[]) {
  return [...topics, ...G];
}
function project(...topics: string[]) {
  return [...topics, ...J];
}
function testprep(...topics: string[]) {
  return [...topics, ...T];
}

/** Bulk-add courses that share the same topic template. */
function bulk(names: string[], topics: string[]) {
  const out: Record<string, string[]> = {};
  for (const name of names) out[name] = topics;
  return out;
}

const CORE: Record<string, string[]> = {
  "Calc 1": [
    "Limits",
    "Continuity",
    "Derivatives",
    "Product / Quotient Rule",
    "Chain Rule",
    "Related Rates",
    "Optimization",
    "Implicit Differentiation",
    "Mean Value Theorem",
    "Exam 1 review",
    "Exam 2 review",
    "Final exam review",
  ],
  "Calc 2": [
    "Integration by parts",
    "U-substitution",
    "Trig sub",
    "Partial fractions",
    "Improper integrals",
    "Sequences",
    "Series",
    "Taylor series",
    "Polar coordinates",
    "Parametric equations",
    "Vectors and applications",
    "Exam 1 review",
    "Exam 2 review",
    "Final exam review",
  ],
  "Calc 3": [
    "Vectors in 3D",
    "Partial derivatives",
    "Gradients",
    "Multiple integrals",
    "Line integrals",
    "Green's Theorem",
    "Stokes' Theorem",
    "Exam review",
    "Final exam review",
  ],
  "Linear Algebra": [
    "Matrices",
    "Row reduction",
    "Determinants",
    "Eigenvalues / eigenvectors",
    "Vector spaces",
    "Linear transformations",
    "Orthogonality",
    "Exam review",
    "Final exam review",
  ],
  "Discrete Math": [
    "Logic & proofs",
    "Sets",
    "Functions & relations",
    "Combinatorics",
    "Graph theory",
    "Induction",
    "Recurrence relations",
    "Exam review",
    "Final exam review",
  ],
  "Differential Equations": [
    "Separable ODEs",
    "First-order linear",
    "Second-order ODEs",
    "Laplace transforms",
    "Systems of ODEs",
    "Exam review",
    "Final exam review",
  ],
  "Physics 1": [
    "Kinematics",
    "Newton's laws",
    "Forces & free-body diagrams",
    "Energy & work",
    "Momentum",
    "Rotation",
    "Oscillations",
    "Exam review",
    "Final exam review",
  ],
  "Physics 2": [
    "Electric fields",
    "Gauss's law",
    "Circuits",
    "Magnetism",
    "Induction",
    "Waves & optics",
    "Exam review",
    "Final exam review",
  ],
  "Chemistry 1": [
    "Stoichiometry",
    "Atomic structure",
    "Periodic trends",
    "Bonding",
    "Thermochemistry",
    "Gases",
    "Exam review",
    "Final exam review",
  ],
  "Chemistry 2": [
    "Equilibrium",
    "Acids & bases",
    "Kinetics",
    "Electrochemistry",
    "Thermodynamics",
    "Exam review",
    "Final exam review",
  ],
  "Biology 1": [
    "Cell structure",
    "Macromolecules",
    "Metabolism",
    "Genetics basics",
    "Exam review",
    "Final exam review",
  ],
  "Intro to Programming": [
    "Variables & types",
    "Conditionals",
    "Loops",
    "Functions",
    "Arrays / lists",
    "File I/O",
    "Debugging",
    "Project help",
    "Exam review",
  ],
  "Data Structures": [
    "Arrays & lists",
    "Stacks & queues",
    "Linked lists",
    "Trees",
    "Heaps",
    "Hash tables",
    "Graphs",
    "Sorting",
    "Big-O analysis",
    "Exam review",
    "Final exam review",
  ],
  "Algorithms": [
    "Divide & conquer",
    "Dynamic programming",
    "Greedy algorithms",
    "Graph algorithms",
    "Complexity",
    "Exam review",
    "Final exam review",
  ],
  "Computer Organization": [
    "Binary & numbering",
    "Assembly basics",
    "CPU pipeline",
    "Memory hierarchy",
    "Caches",
    "Exam review",
    "Final exam review",
  ],
  "Software Engineering": [
    "Requirements",
    "UML / design",
    "Agile / Scrum",
    "Testing",
    "Git workflows",
    "Design patterns",
    "Project milestone help",
    "Exam review",
  ],
  "Databases": [
    "ER diagrams",
    "SQL selects",
    "Joins",
    "Normalization",
    "Transactions",
    "Exam review",
    "Final exam review",
  ],
  "Statistics": [
    "Descriptive stats",
    "Probability",
    "Distributions",
    "Hypothesis testing",
    "Confidence intervals",
    "Regression",
    "Exam review",
    "Final exam review",
  ],
  "Economics": [
    "Supply & demand",
    "Elasticity",
    "Market structures",
    "GDP & inflation",
    "Exam review",
    "Final exam review",
  ],
  "Psychology": [
    "Research methods",
    "Memory & learning",
    "Development",
    "Social psychology",
    "Exam review",
    "Final exam review",
  ],
  "English Comp": [
    "Thesis statements",
    "Essay structure",
    "Citations / MLA / APA",
    "Peer review",
    "Rhetorical analysis",
    "Research paper help",
  ],
  "Public Speaking": [
    "Speech outline",
    "Persuasive speech",
    "Informative speech",
    "Delivery practice",
    "Visual aids",
  ],
  "College Algebra": stem("Functions", "Polynomials", "Rational expressions", "Exponentials & logs"),
  "Pre-Calculus": stem("Functions", "Trigonometry", "Analytic geometry", "Sequences"),
  "Trigonometry": stem("Unit circle", "Identities", "Graphing trig functions", "Law of sines / cosines"),
  "Organic Chemistry 1": lab("Nomenclature", "Stereochemistry", "Reaction mechanisms", "Alkyl halides", "Alkenes & alkynes"),
  "Organic Chemistry 2": lab("Aromatic chemistry", "Carbonyl chemistry", "Amines", "Spectroscopy (NMR / IR)", "Synthesis problems"),
  "Anatomy & Physiology": lab("Skeletal system", "Muscular system", "Nervous system", "Cardiovascular system", "Lab practical prep"),
  "Microbiology": lab("Cell structure", "Metabolism", "Genetics of bacteria", "Viruses", "Lab techniques"),
  "Genetics": lab("Mendelian genetics", "Linkage & mapping", "Population genetics", "Molecular genetics"),
  "Cell Biology": lab("Membrane transport", "Organelles", "Cell signaling", "Cell cycle"),
  "Statics": stem("Free-body diagrams", "Equilibrium", "Trusses", "Friction"),
  "Dynamics": stem("Kinematics", "Newton's laws", "Work-energy", "Impulse-momentum"),
  "Circuits": stem("Ohm's law", "Kirchhoff's laws", "Thevenin / Norton", "AC analysis"),
  "Digital Logic": stem("Boolean algebra", "Combinational circuits", "Sequential logic", "Finite state machines"),
  "Operating Systems": stem("Processes & threads", "Scheduling", "Memory management", "File systems", "Synchronization"),
  "Computer Networks": stem("OSI / TCP-IP", "Routing", "Transport layer", "Application protocols"),
  "Cybersecurity": stem("Cryptography basics", "Network security", "Web security", "Threat modeling"),
  "Web Development": project("HTML / CSS", "JavaScript", "React / frontend", "APIs & backends"),
  "Machine Learning": project("Linear models", "Classification", "Neural networks", "Model evaluation"),
  "Artificial Intelligence": stem("Search algorithms", "Knowledge representation", "Planning", "ML basics"),
  "Human-Computer Interaction": project("User research", "Prototyping", "Usability testing", "Design critique"),
  "Accounting": stem("Journal entries", "Financial statements", "Adjusting entries"),
  "Finance": stem("Time value of money", "Bonds & stocks", "Capital budgeting", "Risk & return"),
  "Marketing": essay("Segmentation", "Branding", "Marketing mix", "Case studies"),
  "Management": essay("Organizational behavior", "Leadership", "Operations basics", "Case studies"),
  "Microeconomics": stem("Supply & demand", "Elasticity", "Consumer choice", "Market structures"),
  "Macroeconomics": stem("GDP & inflation", "Fiscal policy", "Monetary policy", "International trade"),
  "Nursing Fundamentals": lab("Vital signs", "Patient assessment", "Medication administration", "Clinical skills"),
  "Pharmacology": stem("Drug classes", "Dosage calculations", "Adverse effects"),
  "Political Science": essay("Constitutional principles", "Political theory", "Comparative politics", "Policy analysis"),
  "Sociology": essay("Research methods", "Social institutions", "Inequality"),
  "Philosophy": essay("Logic", "Ethics", "Metaphysics"),
  "US History": essay("Colonial era", "Civil War & Reconstruction", "20th century", "Primary source analysis"),
  "World History": essay("Ancient civilizations", "Early modern period", "Industrialization"),
  "Art History": essay("Visual analysis", "Periods & movements", "Museum paper help"),
  "Music Theory": stem("Rhythm & meter", "Harmony", "Ear training", "Composition"),
  Spanish: lang(),
  French: lang(),
  "Technical Writing": essay("Reports", "Documentation", "Visual communication"),
  "Research Methods": essay("Literature review", "Study design", "Statistics basics", "APA / MLA formatting"),
  "Senior Capstone": project("Project planning", "Documentation", "Demo rehearsal"),
};

export const SUBJECT_TOPICS: Record<string, string[]> = {
  ...CORE,
  ...bulk(
    [
      "Applied Calculus",
      "Business Calculus",
      "Multivariable Calculus",
      "Vector Calculus",
      "Honors Calculus",
      "AP Calculus AB",
      "AP Calculus BC",
      "Finite Mathematics",
      "Quantitative Reasoning",
      "Math for Liberal Arts",
      "Math for Elementary Teachers",
      "Intermediate Algebra",
      "Elementary Algebra",
      "Developmental Math",
      "Abstract Algebra",
      "Number Theory",
      "Real Analysis",
      "Complex Analysis",
      "Topology",
      "Numerical Methods",
      "Mathematical Modeling",
      "Probability Theory",
      "Mathematical Statistics",
      "Set Theory",
      "Combinatorics",
      "Graph Theory (Math)",
      "Geometry",
      "Euclidean Geometry",
      "Differential Geometry",
      "Partial Differential Equations",
      "Fourier Analysis",
      "Linear Programming",
      "Optimization",
      "Game Theory",
      "Actuarial Mathematics",
      "Biostatistics",
      "AP Statistics",
    ],
    [...P],
  ),
  ...bulk(
    [
      "Physics 3",
      "Modern Physics",
      "Classical Mechanics",
      "Electromagnetism",
      "Quantum Mechanics",
      "Thermodynamics",
      "Statistical Mechanics",
      "Optics",
      "Nuclear Physics",
      "Particle Physics",
      "Astrophysics",
      "Geophysics",
      "Biophysics",
      "Physics Lab",
      "Honors Physics",
      "AP Physics 1",
      "AP Physics 2",
      "AP Physics C: Mechanics",
      "AP Physics C: E&M",
      "Conceptual Physics",
      "Physical Science",
    ],
    [...P],
  ),
  ...bulk(
    [
      "General Chemistry",
      "Honors Chemistry",
      "Analytical Chemistry",
      "Physical Chemistry",
      "Biochemistry",
      "Inorganic Chemistry",
      "Environmental Chemistry",
      "Polymer Chemistry",
      "Medicinal Chemistry",
      "Forensic Chemistry",
      "Materials Chemistry",
      "Quantitative Analysis",
      "Instrumental Analysis",
      "AP Chemistry",
    ],
    [...L],
  ),
  ...bulk(
    [
      "Biology 2",
      "General Biology",
      "Honors Biology",
      "Ecology",
      "Evolution",
      "Botany",
      "Zoology",
      "Marine Biology",
      "Molecular Biology",
      "Immunology",
      "Virology",
      "Neuroscience",
      "Physiology",
      "Pathophysiology",
      "Anatomy",
      "Human Anatomy",
      "Comparative Anatomy",
      "Developmental Biology",
      "Plant Biology",
      "Wildlife Biology",
      "Conservation Biology",
      "Bioinformatics",
      "Biotechnology",
      "AP Biology",
    ],
    [...L],
  ),
  ...bulk(
    [
      "Medical Terminology",
      "Health Assessment",
      "Pathophysiology for Nursing",
      "Medical-Surgical Nursing",
      "Pediatric Nursing",
      "OB/GYN Nursing",
      "Maternal-Child Nursing",
      "Psychiatric Nursing",
      "Mental Health Nursing",
      "Community Health Nursing",
      "Geriatric Nursing",
      "Critical Care Nursing",
      "Nursing Pharmacology",
      "Nursing Research",
      "NCLEX-RN Prep",
      "NCLEX-PN Prep",
      "Clinical Rotations",
      "Public Health",
      "Epidemiology",
      "Global Health",
      "Health Policy",
      "Nutrition Science",
      "Human Nutrition",
      "Sports Nutrition",
      "Kinesiology",
      "Exercise Physiology",
      "Sports Medicine",
      "Athletic Training",
      "Physical Therapy Fundamentals",
      "Occupational Therapy Fundamentals",
      "Speech-Language Pathology",
      "Dental Anatomy",
      "Dental Hygiene",
      "Radiologic Technology",
      "Emergency Medical Services",
      "Paramedicine",
      "Health Informatics",
    ],
    [...L, "Clinical skills", "Case studies"],
  ),
  ...bulk(
    [
      "Civil Engineering",
      "Mechanical Engineering",
      "Electrical Engineering",
      "Chemical Engineering",
      "Aerospace Engineering",
      "Biomedical Engineering",
      "Industrial Engineering",
      "Environmental Engineering",
      "Computer Engineering",
      "Software Engineering (Engineering)",
      "Materials Science",
      "Engineering Statistics",
      "Engineering Economics",
      "Fluid Mechanics",
      "Heat Transfer",
      "Control Systems",
      "Signal Processing",
      "Power Systems",
      "Structural Analysis",
      "Reinforced Concrete Design",
      "Steel Design",
      "Transportation Engineering",
      "Geotechnical Engineering",
      "Surveying",
      "CAD / SolidWorks",
      "MATLAB for Engineers",
      "Finite Element Analysis",
      "Robotics",
      "Mechatronics",
      "Manufacturing Processes",
      "Quality Engineering",
      "Systems Engineering",
      "Engineering Ethics",
      "Senior Design (Engineering)",
      "Statics & Dynamics",
      "Mechanics of Materials",
      "Thermodynamics (Engineering)",
      "Circuit Analysis",
      "Electronics",
      "Digital Systems",
      "Embedded Systems",
      "VLSI Design",
      "Hydraulics",
      "Environmental Engineering Design",
      "Water Resources",
      "Construction Management",
    ],
    [...P, "Design project help"],
  ),
  ...bulk(
    [
      "Object-Oriented Programming",
      "Java Programming",
      "Python Programming",
      "C Programming",
      "C++ Programming",
      "C# Programming",
      "JavaScript Programming",
      "Rust Programming",
      "Go Programming",
      "Swift Programming",
      "Kotlin Programming",
      "R Programming",
      "MATLAB Programming",
      "Compilers",
      "Programming Languages",
      "Computer Architecture",
      "Parallel Computing",
      "Distributed Systems",
      "Cloud Computing",
      "DevOps",
      "Site Reliability Engineering",
      "Mobile App Development",
      "iOS Development",
      "Android Development",
      "Game Development",
      "Computer Graphics",
      "Data Mining",
      "Big Data",
      "Data Visualization",
      "Natural Language Processing",
      "Computer Vision",
      "Reinforcement Learning",
      "Deep Learning",
      "Information Security",
      "Ethical Hacking",
      "IT Fundamentals",
      "Systems Analysis & Design",
      "Software Testing",
      "UI/UX Design",
      "Product Management (Tech)",
      "Technical Interview Prep",
      "AP Computer Science A",
      "AP Computer Science Principles",
      "Information Systems",
      "Business Analytics",
      "Data Science",
      "Data Engineering",
      "Blockchain",
      "Quantum Computing",
      "High Performance Computing",
      "Human-Robot Interaction",
      "Computational Biology",
      "Scientific Computing",
      "Full Stack Development",
      "Backend Development",
      "Frontend Development",
      "API Design",
      "Microservices",
      "Linux Administration",
      "Network Administration",
    ],
    [...J],
  ),
  ...bulk(
    [
      "Business Statistics",
      "Operations Management",
      "Supply Chain Management",
      "Logistics",
      "Entrepreneurship",
      "Small Business Management",
      "International Business",
      "Business Law",
      "Commercial Law",
      "Real Estate Principles",
      "Insurance Principles",
      "Actuarial Science",
      "Corporate Finance",
      "Investments",
      "Portfolio Management",
      "Financial Modeling",
      "Financial Accounting",
      "Managerial Accounting",
      "Intermediate Accounting",
      "Advanced Accounting",
      "Tax Accounting",
      "Auditing",
      "Cost Accounting",
      "QuickBooks",
      "Excel for Business",
      "Business Communication",
      "Organizational Leadership",
      "Human Resource Management",
      "Business Ethics",
      "Strategic Management",
      "Project Management",
      "Agile Project Management",
      "Six Sigma",
      "Quality Management",
      "E-Commerce",
      "Digital Marketing",
      "Social Media Marketing",
      "Consumer Behavior",
      "Sales Management",
      "Negotiation",
      "Business Analytics (MBA)",
      "Intro to Business",
      "Principles of Management",
      "Principles of Marketing",
      "Personal Finance",
      "Real Estate Finance",
    ],
    [...H, "Case studies"],
  ),
  ...bulk(
    [
      "Criminal Law",
      "Constitutional Law",
      "Torts",
      "Contracts",
      "Property Law",
      "Evidence",
      "Civil Procedure",
      "Legal Writing",
      "Legal Research",
      "LSAT Prep",
      "Criminal Justice",
      "Criminology",
      "Forensic Science",
      "Criminal Investigation",
      "Corrections",
      "Policing",
      "Cybercrime",
      "Juvenile Justice",
      "Homeland Security",
      "Paralegal Studies",
      "Court Reporting",
      "Ethics in Criminal Justice",
    ],
    [...W, "Case briefs"],
  ),
  ...bulk(
    [
      "Developmental Psychology",
      "Cognitive Psychology",
      "Abnormal Psychology",
      "Clinical Psychology",
      "Biological Psychology",
      "Personality Psychology",
      "Industrial-Organizational Psychology",
      "Forensic Psychology",
      "Behavioral Neuroscience",
      "Counseling Theories",
      "Social Work Practice",
      "Child Psychology",
      "Adolescent Psychology",
      "Health Psychology",
      "Sports Psychology",
      "Educational Psychology",
      "Experimental Psychology",
      "Psychometrics",
      "Psychology Statistics",
      "Intro to Psychology",
      "AP Psychology",
    ],
    [...H, "Research paper help"],
  ),
  ...bulk(
    [
      "Cultural Anthropology",
      "Physical Anthropology",
      "Archaeology",
      "Linguistics",
      "Introduction to Linguistics",
      "Phonetics",
      "Syntax",
      "Semantics",
      "Human Geography",
      "World Regional Geography",
      "GIS",
      "Remote Sensing",
      "Urban Geography",
      "International Relations",
      "Comparative Politics",
      "Public Policy",
      "Public Administration",
      "Urban Planning",
      "Social Problems",
      "Race & Ethnic Relations",
      "Gender Studies",
      "Women's Studies",
      "LGBTQ Studies",
      "Religion",
      "World Religions",
      "Theology",
      "Ethics",
      "Bioethics",
      "Business Ethics",
      "Critical Thinking",
      "Formal Logic",
      "Symbolic Logic",
      "Communication Studies",
      "Mass Communication",
      "Interpersonal Communication",
      "Conflict Resolution",
      "Peace Studies",
      "Human Rights",
      "AP Human Geography",
      "AP Comparative Government",
      "AP US Government",
    ],
    [...W],
  ),
  ...bulk(
    [
      "Creative Writing",
      "Poetry Writing",
      "Fiction Writing",
      "Nonfiction Writing",
      "Journalism",
      "Media Studies",
      "Film Studies",
      "Cinema Studies",
      "Theater",
      "Acting",
      "Drama",
      "Shakespeare",
      "American Literature",
      "British Literature",
      "World Literature",
      "Literary Analysis",
      "Rhetoric & Composition",
      "Composition 1",
      "Composition 2",
      "Reading & Writing",
      "Advanced Composition",
      "Professional Writing",
      "Science Writing",
      "Grant Writing",
      "Literature Survey",
      "African American Literature",
      "Latin American Literature",
      "Postcolonial Literature",
      "Mythology",
      "Classics",
      "AP English Language",
      "AP English Literature",
    ],
    [...W],
  ),
  ...bulk(
    [
      "German",
      "Italian",
      "Chinese (Mandarin)",
      "Japanese",
      "Korean",
      "Arabic",
      "Latin",
      "Portuguese",
      "Russian",
      "Hindi",
      "American Sign Language (ASL)",
      "ESL / English as a Second Language",
      "AP Spanish Language",
      "AP Spanish Literature",
      "AP French Language",
      "AP Chinese Language",
      "AP Japanese Language",
      "AP German Language",
      "AP Latin",
    ],
    [...G],
  ),
  ...bulk(
    [
      "Drawing",
      "Painting",
      "Sculpture",
      "Photography",
      "Graphic Design",
      "Industrial Design",
      "Architecture Studio",
      "Architectural Design",
      "Interior Design",
      "Fashion Design",
      "Animation",
      "Digital Media",
      "Ceramics",
      "Printmaking",
      "Visual Arts",
      "Studio Art",
      "Art Appreciation",
      "Design Fundamentals",
      "Color Theory",
      "Typography",
      "UX Design",
      "Product Design",
      "Web Design",
      "Motion Graphics",
      "3D Modeling",
      "Game Art",
      "AP Studio Art",
      "AP Art History",
    ],
    [...J, "Critique session"],
  ),
  ...bulk(
    [
      "Music Appreciation",
      "Piano",
      "Guitar",
      "Voice / Choir",
      "Band",
      "Orchestra",
      "Music History",
      "Jazz History",
      "Music Production",
      "Audio Engineering",
      "AP Music Theory",
    ],
    [...H, "Performance prep"],
  ),
  ...bulk(
    [
      "European History",
      "African American History",
      "Latin American History",
      "Middle Eastern History",
      "Asian History",
      "Ancient History",
      "Medieval History",
      "Military History",
      "History of Science",
      "Historiography",
      "AP US History",
      "AP World History",
      "AP European History",
    ],
    [...W],
  ),
  ...bulk(
    [
      "Environmental Science",
      "Earth Science",
      "Geology",
      "Meteorology",
      "Climatology",
      "Oceanography",
      "Astronomy",
      "Planetary Science",
      "Space Science",
      "Natural Disasters",
      "Sustainability",
      "Renewable Energy",
      "AP Environmental Science",
    ],
    [...L],
  ),
  ...bulk(
    [
      "Agricultural Science",
      "Horticulture",
      "Animal Science",
      "Food Science",
      "Viticulture",
      "Forestry",
      "Soil Science",
      "Agribusiness",
    ],
    [...L],
  ),
  ...bulk(
    [
      "Early Childhood Education",
      "Elementary Education",
      "Secondary Education",
      "Special Education",
      "Curriculum & Instruction",
      "Classroom Management",
      "Teaching Methods",
      "Literacy Instruction",
      "Reading Education",
      "Math Education",
      "Science Education",
      "Educational Technology",
      "Assessment in Education",
      "School Counseling",
      "Instructional Design",
      "Adult Education",
      "TESOL / TEFL",
    ],
    [...J, "Lesson planning"],
  ),
  ...bulk(
    [
      "SAT Prep",
      "ACT Prep",
      "GRE Prep",
      "GMAT Prep",
      "MCAT Prep",
      "DAT Prep",
      "OAT Prep",
      "PCAT Prep",
      "LSAT Prep (General)",
      "CFA Level 1 Prep",
      "CPA Exam Prep",
      "FE Exam Prep (EIT)",
      "PE Exam Prep",
      "CompTIA A+ Prep",
      "CompTIA Network+ Prep",
      "CompTIA Security+ Prep",
      "AWS Certification Prep",
      "Google Cloud Certification Prep",
      "Bar Exam Prep",
      "USMLE Step 1 Prep",
      "USMLE Step 2 Prep",
      "PMP Certification Prep",
      "Real Estate License Prep",
      "Series 7 Prep",
      "Praxis Exam Prep",
    ],
    [...T],
  ),
  ...bulk(
    [
      "Intro to Sociology",
      "Intro to Anthropology",
      "Intro to Philosophy",
      "Intro to Political Science",
      "Intro to Economics",
      "Intro to Psychology",
      "Intro to Communication",
      "Intro to Criminal Justice",
      "Intro to Engineering",
      "Intro to Computer Science",
      "Intro to Statistics",
      "Intro to Biology",
      "Intro to Chemistry",
      "Intro to Physics",
      "Intro to Astronomy",
      "Intro to Geology",
      "Intro to Art",
      "Intro to Music",
      "Intro to Theater",
      "Intro to Film",
      "Intro to Nutrition",
      "Intro to Public Health",
      "Intro to Nursing",
      "Intro to Education",
      "Intro to Architecture",
      "Intro to Data Science",
      "First-Year Seminar",
      "University Studies",
      "Freshman Composition",
      "Senior Seminar",
      "Honors Seminar",
      "Independent Study",
      "Internship / Co-op",
      "Study Abroad Prep",
    ],
    [...H],
  ),
  ...bulk(
    [
      "English Composition I",
      "English Composition II",
      "College Writing I",
      "College Writing II",
      "Western Civilization I",
      "Western Civilization II",
      "American History I",
      "American History II",
      "American Government",
      "State & Local Government",
      "Introduction to Humanities",
      "Ethics & Society",
      "Global Studies",
      "College Success",
      "Information Literacy",
    ],
    [...H],
  ),
  ...bulk(
    [
      "IB Math Analysis & Approaches HL",
      "IB Math Analysis & Approaches SL",
      "IB Math Applications HL",
      "IB Math Applications SL",
      "IB Physics HL",
      "IB Chemistry HL",
      "IB Biology HL",
      "IB Computer Science HL",
      "IB Economics HL",
      "IB History HL",
      "IB English A HL",
      "IB Psychology HL",
      "Dual Enrollment English",
      "Dual Enrollment Calculus",
      "Dual Enrollment Biology",
      "Dual Enrollment Chemistry",
      "Dual Enrollment US History",
      "CLEP College Algebra",
      "CLEP Calculus",
      "CLEP Biology",
      "CLEP Intro Psychology",
      "CLEP Financial Accounting",
      "AP Precalculus",
      "AP Microeconomics",
      "AP Macroeconomics",
      "AP African American Studies",
      "AP Research",
      "AP Seminar",
    ],
    [...T],
  ),
  ...bulk(
    [
      "Welding",
      "Automotive Technology",
      "HVAC",
      "Electrical Trades",
      "Culinary Arts",
      "Hospitality Management",
      "Event Planning",
      "Fire Science",
      "Law Enforcement Academy",
      "Veterinary Technology",
      "Pharmacy Technician",
      "Medical Assisting",
      "Surgical Technology",
      "Respiratory Therapy",
      "Phlebotomy",
      "Medical Coding & Billing",
      "Physical Therapist Assistant",
      "Dental Assisting",
    ],
    [...L, "Certification prep"],
  ),
  ...bulk(
    [
      "Dutch",
      "Swedish",
      "Polish",
      "Turkish",
      "Vietnamese",
      "Thai",
      "Hebrew",
      "Greek (Modern)",
      "Persian (Farsi)",
      "Urdu",
      "Cantonese",
      "AP Italian Language",
    ],
    [...G],
  ),
  ...bulk(
    [
      "Tensor Calculus",
      "Stochastic Processes",
      "Time Series Analysis",
      "Multivariate Statistics",
      "Bayesian Statistics",
      "Operations Research",
      "Financial Mathematics",
      "Cryptography (Math)",
      "Monte Carlo Methods",
    ],
    [...P],
  ),
  ...bulk(
    [
      "Solid State Physics",
      "Medical Physics",
      "Computational Physics",
      "Quantum Chemistry",
      "Spectroscopy",
      "Toxicology",
      "Histology",
      "Embryology",
      "Parasitology",
    ],
    [...L],
  ),
  ...bulk(
    [
      "Formal Methods",
      "Software Architecture",
      "Containerization (Docker/K8s)",
      "Kubernetes",
      "Penetration Testing",
      "Digital Forensics",
      "NoSQL Databases",
      "MLOps",
      "Generative AI",
      "Prompt Engineering",
      "LeetCode Prep",
      "System Design Interview Prep",
      "Verilog / VHDL",
    ],
    [...J],
  ),
  ...bulk(
    [
      "Structural Engineering",
      "Traffic Engineering",
      "HVAC Design",
      "Green Building (LEED)",
      "Aerodynamics",
      "Biomechanics",
      "Biomaterials",
      "Petroleum Engineering",
      "Process Control",
      "Combustion Engines",
    ],
    [...P, "Design project help"],
  ),
  ...bulk(
    [
      "Family Law",
      "Intellectual Property Law",
      "Immigration Law",
      "Tax Law",
      "Environmental Law",
      "Moot Court",
      "MCAT Biology",
      "MCAT Chemistry",
      "MCAT Physics",
      "MCAT CARS",
      "Interview Prep (Pre-Health)",
      "Personal Statement Workshop",
    ],
    [...W, "Case briefs"],
  ),
  ...bulk(
    [
      "Addiction Studies",
      "Marriage & Family Therapy",
      "Crisis Intervention",
      "Trauma-Informed Care",
      "Cross-Cultural Psychology",
      "Medical Sociology",
      "Criminology Theory",
      "Model United Nations Prep",
    ],
    [...H, "Research paper help"],
  ),
  ...bulk(
    [
      "Screenwriting",
      "Film Production",
      "Video Editing",
      "Podcasting",
      "Digital Photography",
      "Illustration",
      "Brand Identity Design",
      "Music Composition",
      "Electronic Music Production",
    ],
    [...J, "Critique session"],
  ),
  ...bulk(
    [
      "Calc I",
      "Calc II",
      "Calc III",
      "General Chemistry I",
      "General Chemistry II",
      "Organic Chem I",
      "Organic Chem II",
      "General Biology I",
      "General Biology II",
      "General Physics I",
      "General Physics II",
      "Engineering Physics I",
      "Engineering Physics II",
      "Data Structures & Algorithms",
      "Capstone Design",
      "Undergraduate Research",
    ],
    [...P],
  ),
  ...bulk(
    [
      "MATH 101",
      "MATH 102",
      "MATH 151",
      "MATH 152",
      "MATH 251",
      "MATH 252",
      "MATH 253",
      "STAT 101",
      "STAT 201",
      "STAT 301",
      "CHEM 101",
      "CHEM 102",
      "CHEM 201",
      "CHEM 202",
      "CHEM 301",
      "PHYS 101",
      "PHYS 102",
      "PHYS 201",
      "PHYS 202",
      "BIO 101",
      "BIO 102",
      "BIO 201",
      "BIO 202",
      "BIO 301",
      "ENG 101",
      "ENG 102",
      "ENG 201",
      "PSYC 101",
      "PSYC 201",
      "SOC 101",
      "SOC 201",
      "ECON 101",
      "ECON 102",
      "ECON 201",
      "POLS 101",
      "HIST 101",
      "HIST 102",
      "CS 101",
      "CS 111",
      "CS 201",
      "CS 301",
      "CS 401",
      "ENGR 101",
      "ENGR 102",
      "ACCT 101",
      "ACCT 201",
      "FIN 301",
      "MKTG 301",
      "MGMT 301",
      "NURS 101",
      "NURS 201",
      "NURS 301",
    ],
    [...H],
  ),
  ...bulk(
    [
      "Calculus for Life Sciences",
      "Calculus for Business & Economics",
      "Survey of Calculus",
      "Mathematics for Business",
      "Statistics for Engineers",
      "Statistics for Social Sciences",
      "Regression Analysis",
      "Experimental Design",
      "Nonparametric Statistics",
      "Sampling Theory",
      "Logic for Computer Science",
      "Mathematical Logic",
      "History of Mathematics",
      "Applied Linear Algebra",
      "Matrix Theory",
      "Calculus-Based Statistics",
    ],
    [...P],
  ),
  ...bulk(
    [
      "Cell Biology",
      "Genetics Lab",
      "Microbiology Lab",
      "Organic Chemistry Lab",
      "General Chemistry Lab",
      "Physics Lab I",
      "Physics Lab II",
      "Anatomy & Physiology I",
      "Anatomy & Physiology II",
      "Human Physiology",
      "Microbiology for Health Sciences",
      "Organic Chemistry III",
      "Physical Chemistry II",
      "Inorganic Chemistry II",
      "Environmental Biology",
      "Freshwater Ecology",
      "Population Ecology",
      "Systems Biology",
      "Proteomics",
      "Genomics",
    ],
    [...L],
  ),
  ...bulk(
    [
      "Cardiology",
      "Neuroanatomy",
      "Oncology Nursing",
      "Pediatric Dentistry",
      "Optometry Fundamentals",
      "Veterinary Anatomy",
      "Veterinary Pathology",
      "Dental Materials",
      "Orthodontics",
      "Prosthodontics",
      "Anesthesiology",
      "Emergency Medicine",
      "Family Medicine Clerkship",
      "Internal Medicine Clerkship",
      "Surgery Clerkship",
      "Obstetrics Clerkship",
      "Pediatrics Clerkship",
      "Psychiatry Clerkship",
      "Clinical Skills (Med)",
      "Board Exam Review (Med)",
      "Nurse Practitioner Fundamentals",
      "Physician Assistant Fundamentals",
      "Midwifery",
      "Lactation Consultant Training",
      "Medical Laboratory Science",
      "Clinical Chemistry",
      "Hematology (Lab)",
      "Immunohematology",
    ],
    [...L, "Clinical skills"],
  ),
  ...bulk(
    [
      "Web Development with React",
      "Web Development with Vue",
      "Django Web Development",
      "Flask Web Development",
      "Spring Boot Development",
      ".NET Development",
      "Unity Game Development",
      "Unreal Engine Development",
      "TypeScript Programming",
      "PHP Programming",
      "Ruby Programming",
      "Scala Programming",
      "Elixir Programming",
      "Assembly Language",
      "FPGA Design",
      "Internet of Things (IoT)",
      "Edge Computing",
      "AR/VR Development",
      "Computer Networks II",
      "Wireless Networks",
      "Database Administration",
      "PostgreSQL",
      "MySQL Administration",
      "MongoDB",
      "Redis",
      "Elasticsearch",
      "Apache Spark",
      "Hadoop",
      "ETL Pipelines",
      "Data Warehousing",
      "Business Intelligence",
      "Tableau",
      "Power BI",
      "Salesforce Administration",
      "SAP Fundamentals",
      "ITIL Certification Prep",
      "Cisco CCNA Prep",
      "Cisco CCNP Prep",
    ],
    [...J],
  ),
  ...bulk(
    [
      "MBA Finance",
      "MBA Marketing",
      "MBA Operations",
      "MBA Strategy",
      "MBA Accounting",
      "MBA Data Analytics",
      "Executive MBA Seminar",
      "Venture Capital",
      "Private Equity",
      "Mergers & Acquisitions",
      "International Finance",
      "Derivatives",
      "Fixed Income",
      "Behavioral Finance",
      "Real Estate Investment",
      "Property Management",
      "Commercial Real Estate",
      "Nonprofit Management",
      "Social Entrepreneurship",
      "Franchise Management",
      "Retail Management",
      "Hospitality Finance",
      "Revenue Management",
      "Brand Management",
      "Product Marketing",
      "Content Marketing",
      "SEO / SEM",
      "Email Marketing",
      "Marketing Analytics",
      "Customer Analytics",
    ],
    [...H, "Case studies"],
  ),
  ...bulk(
    [
      "Public Speaking",
      "Debate",
      "Forensics (Speech)",
      "Technical Communication",
      "Business Presentations",
      "Intercultural Communication",
      "Health Communication",
      "Science Communication",
      "Digital Storytelling",
      "Copywriting",
      "Editing & Proofreading",
      "Publishing",
      "Literary Magazine Workshop",
      "Translation Studies",
      "Comparative Literature",
      "Medieval Literature",
      "Victorian Literature",
      "Modern American Literature",
      "Contemporary Fiction",
      "Science Fiction Literature",
      "Fantasy Literature",
      "Graphic Novels",
      "Comics Studies",
      "Pop Culture Studies",
      "Celebrity Culture",
      "Film & Television Studies",
      "Documentary Studies",
      "Animation History",
      "Game Studies",
      "Media Ethics",
    ],
    [...W],
  ),
  ...bulk(
    [
      "AP 2D Art & Design",
      "AP 3D Art & Design",
      "AP Drawing",
      "AP Environmental Science (Advanced)",
      "AP Physics: Algebra-Based",
      "AP Physics: Calculus-Based",
      "AP Computer Science (Legacy)",
      "AP World Languages Workshop",
      "CLEP American Literature",
      "CLEP Analyzing Literature",
      "CLEP College Composition",
      "CLEP Humanities",
      "CLEP Natural Sciences",
      "CLEP Social Sciences",
      "CLEP Western Civilization I",
      "CLEP Western Civilization II",
      "CLEP American Government",
      "CLEP History of the US I",
      "CLEP History of the US II",
      "CLEP Human Growth & Development",
      "CLEP Principles of Marketing",
      "CLEP Principles of Management",
      "CLEP Information Systems",
      "CLEP Business Law",
      "DSST Ethics in Technology",
      "DSST Fundamentals of Counseling",
      "DSST Lifespan Development",
    ],
    [...T],
  ),
  ...bulk(
    [
      "Plumbing",
      "Carpentry",
      "Masonry",
      "Cosmetology",
      "Esthetics",
      "Barbering",
      "Commercial Driving (CDL)",
      "Aviation Maintenance",
      "Drone Pilot Certification",
      "OSHA Safety Training",
      "Forklift Certification",
      "Blueprint Reading",
      "Construction Estimating",
      "Landscaping",
      "Arboriculture",
      "Greenhouse Management",
      "Aquaculture",
      "Equine Science",
      "Veterinary Assisting",
      "Dog Grooming",
      "Pet Care Technician",
      "Child Development Associate (CDA)",
      "Early Intervention",
      "Behavior Technician (RBT)",
      "Personal Training Certification",
      "Group Fitness Instruction",
      "Yoga Teacher Training",
      "Massage Therapy",
      "Acupuncture Fundamentals",
      "Herbal Medicine",
    ],
    [...L, "Certification prep"],
  ),
  ...bulk(
    [
      "Bengali",
      "Tamil",
      "Telugu",
      "Malayalam",
      "Tagalog",
      "Indonesian",
      "Malay",
      "Finnish",
      "Norwegian",
      "Danish",
      "Czech",
      "Romanian",
      "Hungarian",
      "Ukrainian",
      "Serbian",
      "Bulgarian",
      "Swahili",
      "Amharic",
      "Irish (Gaelic)",
      "Welsh",
      "Scottish Gaelic",
      "Ancient Greek",
      "Biblical Hebrew",
      "Sanskrit",
    ],
    [...G],
  ),
  ...bulk(
    [
      "Atmospheric Science",
      "Physical Geography",
      "Cartography",
      "Geodesy",
      "Hydrology",
      "Mineralogy",
      "Petrology",
      "Stratigraphy",
      "Paleontology",
      "Seismology",
      "Volcanology",
      "Glaciology",
      "Coastal Geography",
      "Biogeography",
      "Landscape Ecology",
      "Restoration Ecology",
      "Wildlife Management",
      "Fisheries Science",
      "Range Management",
      "Urban Ecology",
      "Environmental Impact Assessment",
      "Climate Policy",
      "Energy Policy",
      "Water Policy",
    ],
    [...L],
  ),
  ...bulk(
    [
      "Urban Sociology",
      "Medical Anthropology",
      "Economic Anthropology",
      "Applied Anthropology",
      "Psycholinguistics",
      "Sociolinguistics",
      "Historical Linguistics",
      "Computational Linguistics",
      "Discourse Analysis",
      "Rhetorical Theory",
      "Political Theory",
      "International Law",
      "Diplomacy",
      "Intelligence Studies",
      "National Security Studies",
      "Terrorism Studies",
      "Conflict Studies",
      "Peacebuilding",
      "Development Economics",
      "Labor Economics",
      "Health Economics",
      "Urban Economics",
      "Public Economics",
      "Econometrics",
      "Game Theory (Economics)",
      "Behavioral Economics",
      "Industrial Organization",
      "International Trade Theory",
    ],
    [...W],
  ),
  ...bulk(
    [
      "Stage Management",
      "Costume Design",
      "Set Design",
      "Lighting Design",
      "Sound Design",
      "Directing",
      "Playwriting",
      "Improv Comedy",
      "Stand-Up Comedy Writing",
      "Dance Technique",
      "Ballet",
      "Modern Dance",
      "Hip-Hop Dance",
      "Choreography",
      "Music Performance",
      "Conducting",
      "Opera Workshop",
      "Songwriting",
      "Music Business",
      "Arts Administration",
      "Museum Studies",
      "Curatorial Studies",
      "Gallery Management",
      "Art Conservation",
      "Fashion Merchandising",
      "Textile Design",
      "Jewelry Design",
      "Woodworking",
      "Metalworking",
      "Glassblowing",
    ],
    [...J, "Critique session"],
  ),
};
