/** Common undergrad majors for profile + buddy matching. */
export const MAJORS = [
  "Accounting",
  "Aerospace Engineering",
  "Agriculture",
  "Anthropology",
  "Architecture",
  "Art",
  "Biochemistry",
  "Biology",
  "Biomedical Engineering",
  "Business Administration",
  "Chemical Engineering",
  "Chemistry",
  "Civil Engineering",
  "Communications",
  "Computer Engineering",
  "Computer Science",
  "Criminal Justice",
  "Cybersecurity",
  "Data Science",
  "Economics",
  "Education",
  "Electrical Engineering",
  "English",
  "Environmental Science",
  "Finance",
  "Graphic Design",
  "History",
  "Industrial Engineering",
  "Information Systems",
  "Information Technology",
  "International Relations",
  "Journalism",
  "Management",
  "Marketing",
  "Materials Science",
  "Mathematics",
  "Mechanical Engineering",
  "Music",
  "Nursing",
  "Nutrition",
  "Philosophy",
  "Physics",
  "Political Science",
  "Pre-Med",
  "Psychology",
  "Public Health",
  "Public Policy",
  "Sociology",
  "Software Engineering",
  "Statistics",
  "Theatre",
] as const;

export function resolveMajor(raw: string) {
  const cleaned = raw.trim().replace(/\s+/g, " ");
  if (!cleaned || cleaned.length > 60) return "";
  const hit = MAJORS.find((m) => m.toLowerCase() === cleaned.toLowerCase());
  return hit || cleaned;
}
