/** US colleges/universities students can search, pick, and join groups at. */
export const UNIVERSITIES = [
  "Alabama A&M University",
  "Alabama State University",
  "American University",
  "Amherst College",
  "Arizona State University",
  "Auburn University",
  "Auburn University at Montgomery",
  "Baylor University",
  "Boston College",
  "Boston University",
  "Bowling Green State University",
  "Brandeis University",
  "Brigham Young University",
  "Brown University",
  "Bryn Mawr College",
  "Bucknell University",
  "Cal Poly Pomona",
  "Cal Poly San Luis Obispo",
  "California Institute of Technology",
  "Carleton College",
  "Carnegie Mellon University",
  "Case Western Reserve University",
  "Clemson University",
  "Colgate University",
  "College of Charleston",
  "College of William & Mary",
  "Colorado School of Mines",
  "Colorado State University",
  "Columbia University",
  "Cornell University",
  "CUNY City College",
  "Dartmouth College",
  "Davidson College",
  "DePaul University",
  "Drexel University",
  "Duke University",
  "Emory University",
  "Florida A&M University",
  "Florida Atlantic University",
  "Florida International University",
  "Florida State University",
  "Fordham University",
  "George Mason University",
  "George Washington University",
  "Georgetown University",
  "Georgia Institute of Technology",
  "Georgia State University",
  "Gonzaga University",
  "Grinnell College",
  "Harvard University",
  "Harvey Mudd College",
  "Howard University",
  "Illinois Institute of Technology",
  "Indiana University Bloomington",
  "Iowa State University",
  "Jackson State University",
  "James Madison University",
  "Johns Hopkins University",
  "Kansas State University",
  "Kent State University",
  "Lehigh University",
  "Louisiana State University",
  "Loyola University Chicago",
  "Marquette University",
  "Massachusetts Institute of Technology",
  "Miami University",
  "Michigan State University",
  "Michigan Technological University",
  "Middlebury College",
  "Mississippi State University",
  "Morehouse College",
  "New York University",
  "North Carolina A&T State University",
  "North Carolina State University",
  "Northeastern University",
  "Northern Arizona University",
  "Northern Illinois University",
  "Northwestern University",
  "Oberlin College",
  "Ohio State University",
  "Ohio University",
  "Oklahoma State University",
  "Oregon State University",
  "Pennsylvania State University",
  "Pepperdine University",
  "Pomona College",
  "Princeton University",
  "Purdue University",
  "Rensselaer Polytechnic Institute",
  "Rice University",
  "Rochester Institute of Technology",
  "Rutgers University",
  "San Diego State University",
  "San Francisco State University",
  "San Jose State University",
  "Santa Clara University",
  "Southern Methodist University",
  "Spelman College",
  "Stanford University",
  "Stony Brook University",
  "Swarthmore College",
  "Syracuse University",
  "Temple University",
  "Texas A&M University",
  "Texas State University",
  "Texas Tech University",
  "The New School",
  "Tufts University",
  "Tulane University",
  "Tuskegee University",
  "University at Buffalo",
  "University of Alabama",
  "University of Alabama at Birmingham",
  "University of Alabama in Huntsville",
  "University of Alaska Fairbanks",
  "University of Arizona",
  "University of Arkansas",
  "University of California, Berkeley",
  "University of California, Davis",
  "University of California, Irvine",
  "University of California, Los Angeles",
  "University of California, Merced",
  "University of California, Riverside",
  "University of California, San Diego",
  "University of California, Santa Barbara",
  "University of California, Santa Cruz",
  "University of Central Florida",
  "University of Chicago",
  "University of Cincinnati",
  "University of Colorado Boulder",
  "University of Connecticut",
  "University of Delaware",
  "University of Denver",
  "University of Florida",
  "University of Georgia",
  "University of Hawaii at Manoa",
  "University of Houston",
  "University of Idaho",
  "University of Illinois Chicago",
  "University of Illinois Urbana-Champaign",
  "University of Iowa",
  "University of Kansas",
  "University of Kentucky",
  "University of Louisville",
  "University of Maine",
  "University of Maryland",
  "University of Massachusetts Amherst",
  "University of Memphis",
  "University of Miami",
  "University of Michigan",
  "University of Minnesota",
  "University of Mississippi",
  "University of Missouri",
  "University of Montana",
  "University of Nebraska–Lincoln",
  "University of Nevada, Las Vegas",
  "University of Nevada, Reno",
  "University of New Hampshire",
  "University of New Mexico",
  "University of North Carolina at Chapel Hill",
  "University of North Carolina at Charlotte",
  "University of North Dakota",
  "University of North Texas",
  "University of Notre Dame",
  "University of Oklahoma",
  "University of Oregon",
  "University of Pennsylvania",
  "University of Pittsburgh",
  "University of Rhode Island",
  "University of Rochester",
  "University of South Alabama",
  "University of South Carolina",
  "University of South Dakota",
  "University of South Florida",
  "University of Southern California",
  "University of Tennessee",
  "University of Texas at Arlington",
  "University of Texas at Austin",
  "University of Texas at Dallas",
  "University of Texas at San Antonio",
  "University of Utah",
  "University of Vermont",
  "University of Virginia",
  "University of Washington",
  "University of Wisconsin–Madison",
  "University of Wyoming",
  "Vanderbilt University",
  "Vassar College",
  "Villanova University",
  "Virginia Commonwealth University",
  "Virginia Tech",
  "Wake Forest University",
  "Washington State University",
  "Washington University in St. Louis",
  "Wellesley College",
  "Wesleyan University",
  "West Virginia University",
  "Williams College",
  "Worcester Polytechnic Institute",
  "Xavier University of Louisiana",
  "Yale University",
] as const;

export function resolveUniversity(raw: string) {
  const cleaned = raw.trim().replace(/\s+/g, " ");
  if (cleaned.length < 3 || cleaned.length > 80) return "";
  const hit = UNIVERSITIES.find((u) => u.toLowerCase() === cleaned.toLowerCase());
  return hit || cleaned;
}
